# Generated by Django 3.2.6 on 2021-10-24 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Profile Picture'),
        ),
    ]
