# Generated by Django 3.2.6 on 2021-10-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
