# Generated by Django 3.2.6 on 2021-08-22 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alert'),
        ('posts', '0004_auto_20210822_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contents',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='project',
        ),
        migrations.AddField(
            model_name='memo',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Clap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clap', to='posts.comment')),
                ('memo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='clap', to='posts.memo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clap', to='users.userprofile')),
            ],
        ),
    ]
