# Generated by Django 3.2.6 on 2021-08-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alert'),
        ('posts', '0005_auto_20210822_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letread', to='users.userprofile')),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whocanread', to='posts.memo')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readable', to='users.userprofile')),
            ],
        ),
    ]
