# Generated by Django 3.2.6 on 2021-08-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_readable'),
    ]

    operations = [
        migrations.AddField(
            model_name='readable',
            name='muted',
            field=models.IntegerField(default=0, verbose_name='Muted'),
        ),
    ]
