# Generated by Django 3.2.6 on 2021-08-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_readable_muted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='image',
            field=models.FilePathField(blank=True),
        ),
    ]
