# Generated by Django 3.2.6 on 2021-10-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_memo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
