# Generated by Django 3.2.6 on 2021-10-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_memo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clap',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clap', to='posts.comment'),
        ),
        migrations.AlterField(
            model_name='clap',
            name='memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clap', to='posts.memo'),
        ),
    ]
