# Generated by Django 3.2.6 on 2021-11-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='unread',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
