# Generated by Django 3.2.6 on 2021-08-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alert'),
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='member',
        ),
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouping', to='users.userprofile')),
                ('gname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='social.group')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupedby', to='users.userprofile')),
            ],
        ),
    ]
