# Generated by Django 3.2.6 on 2021-08-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20210829_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouping',
            old_name='gname',
            new_name='group',
        ),
    ]
